# Generated by Django 2.1.5 on 2019-02-04 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='favouritequestion',
            table=None,
        ),
    ]
