# Generated by Django 2.1.5 on 2019-02-05 12:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
