# Generated by Django 2.1.5 on 2019-02-04 06:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20190204_0631'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoryReactions',
            new_name='StoryReaction',
        ),
        migrations.RenameModel(
            old_name='StoryTags',
            new_name='StoryTag',
        ),
        migrations.AlterField(
            model_name='story',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='storyreaction',
            table=None,
        ),
        migrations.AlterModelTable(
            name='storytag',
            table=None,
        ),
    ]
