# Generated by Django 2.1.5 on 2019-02-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
