# Generated by Django 2.1.5 on 2019-02-05 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_auto_20190205_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storytag',
            name='tag',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Tag'),
        ),
    ]
